name: Validate

# Only run on PRs to the main branch
on:
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      # Checkout project code
      - uses: actions/checkout@v2
      # Set up python environment
      - run: env
